src/Entities/Sighting.cs
namespace projekt_io.Entities;

public class Sighting {
    public string Id {get; set;} = Guid.NewGuid().ToString();
    
    public string UserId {get; set;}
    public ApplicationUser? User {get; set;}
    
    public string LostReportId {get; set;}
    public LostReport? LostReport {get; set;}
    
    public string LocationId {get; set;}
    public Location? Location {get; set;}
    
    public string Description {get; set;}
    public string PhotoPath {get; set;}
    public DateTime SeenDate { get; set; }
    public DateOnly CreatedAt {get; set;} = DateOnly.FromDateTime(DateTime.UtcNow);
}

src/Controllers/SightingController.cs
using System.Globalization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using projekt_io.DTOs;
using projekt_io.Entities;
using projekt_io.Models;
using projekt_io.Services;

namespace projekt_io.Controllers;

[Route("sighting")]
public class SightingController : Controller{
    private readonly ILogger<SightingController> _logger;
    private readonly ISightingService _sightingService;
    private readonly UserManager<ApplicationUser> _userManager;
    
    public SightingController(ILogger<SightingController> logger, UserManager<ApplicationUser> userManager, ISightingService sightingService) {
        _logger = logger;
        _userManager = userManager;
        _sightingService = sightingService;
    }
    
    [HttpGet("create/{id}")]
    public IActionResult Create(string id) {
        if (String.IsNullOrWhiteSpace(id)) {
            return NotFound();
        }

        var viewModel = new SightingFormViewModel() {
            IsEdit = false,
            LostReportId = id
        };
        
        return View("Form", viewModel);
    }
    
    [HttpPost("create")]
    public async Task<IActionResult> Create(SightingFormViewModel viewModel) {
        if (!ModelState.IsValid) {
            return View("Form", viewModel);
        }
        
        var userId = _userManager.GetUserId(User);
        
        var locationDto = new LocationDto() {
            Latitude = float.Parse(viewModel.Lat, CultureInfo.InvariantCulture),
            Longitude = float.Parse(viewModel.Lng, CultureInfo.InvariantCulture) 
        };

        var sightingDto = new SightingDto() {
            LostReportId = viewModel.LostReportId,
            Description = viewModel.Description.ToLower(),
            Location = locationDto,
            SeenDate = viewModel.SeenDate,
            SeenTime = viewModel.SeenTime,
        };
        
        var result = await _sightingService.CreateAsync(userId, sightingDto, viewModel.Photo);
        
        if (!result) {
            ModelState.AddModelError(string.Empty, "Nie można dodać doniesienia.");
            return View("Form", viewModel);
        }
        
        return RedirectToAction("Index", "Map");
    }
    
    [HttpGet("edit/{id}")]
    public async Task<IActionResult> Edit(string id) {
        var userId = _userManager.GetUserId(User);
        
        var sighting = await _sightingService.GetSightingByIdAsync(userId, id);

        if (sighting == null) {
            return NotFound();
        }

        var viewModel = new SightingFormViewModel() {
            IsEdit = true,
            Id = sighting.Id,
            LostReportId = sighting.LostReport.Id,
            Description = sighting.Description.ToLower(),
            SeenDate = sighting.SeenDate,
            Lat = sighting.Location.Latitude.ToString(CultureInfo.InvariantCulture),
            Lng = sighting.Location.Longitude.ToString(CultureInfo.InvariantCulture)
        };
        
        return View("Form", viewModel);
    }
    
    [HttpPost("edit/{id}")]
    public async Task<IActionResult> Edit(string id, SightingFormViewModel viewModel) {
        viewModel.IsEdit = true;
        viewModel.Id = id;
        viewModel.LostReportId = viewModel.LostReportId;

        if (!ModelState.IsValid) {
            return View("Form", viewModel);
        }
        
        var locationDto = new LocationDto() {
            Latitude = float.Parse(viewModel.Lat, CultureInfo.InvariantCulture),
            Longitude = float.Parse(viewModel.Lng, CultureInfo.InvariantCulture) 
        };

        var sightingDto = new SightingDto() {
            Id = viewModel.Id,
            LostReportId = viewModel.LostReportId,
            Description = viewModel.Description.ToLower(),
            Location = locationDto,
            SeenDate = viewModel.SeenDate,
        };
        
        var userId = _userManager.GetUserId(User);
        
        var result = await _sightingService.UpdateAsync(userId, sightingDto, viewModel.Photo);

        if (!result) {
            ModelState.AddModelError(string.Empty, "Nie udało się edytować doniesienia.");
            return View("Form", viewModel);
        }
        
        return RedirectToAction("Index", "Map");
    }
    
    [Authorize(Roles = "Admin")]
    [HttpPost("delete")]
    public async Task<IActionResult> Delete(string id, string? userId) {
        var result = await _sightingService.DeleteAsync(id);

        if (!result) {
            TempData["Error"] = "Nie udało się usunąć doniesienia.";
            return RedirectToAction("UserProfile", "Profile", new {userId, tab = "sights"});
        }

        TempData["Success"] = "Doniesienie zostało usunięte.";
        return RedirectToAction("UserProfile", "Profile", new {userId, tab = "sights"});
    }
}

src/Views/Sighting/Form.cshtml
@model SightingFormViewModel

@{
    ViewData["Title"] = Model.IsEdit ? "Edytuj doniesienie" : "Dodaj doniesienie";
}

@section Styles {
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <link rel="stylesheet" href="~/css/form.css" />
}

@section Scripts {
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <script src="~/js/form-map.js" defer></script>
    <script src="~/js/form.js" defer></script>
}

<div class="form-header-wrapper">
    <div class="form-header">
        <h1>@(Model.IsEdit ? "Edytuj doniesienie" : "Dodaj doniesienie")</h1>
        <a><i class="fa-solid fa-arrow-left-long"></i> Wróć do mapy</a>
    </div>
    <p class="form-header-description">
        Widziałeś błąkające się zwierzę? Uzupełnij poniższy formularz, aby pomóc w
        jego identyfikacji.
    </p>
</div>

<form asp-controller="Sighting" asp-action="@(Model.IsEdit ? "Edit" : "Create")" asp-route-id="@(Model.IsEdit ? Model.Id : null)" method="post" enctype="multipart/form-data" class="form">
    <input type="hidden" asp-for="LostReportId"/>
    <input type="hidden" asp-for="Id" />
    <input asp-for="Lat" type="hidden" id="Lat"/>
    <input asp-for="Lng" type="hidden" id="Lng"/>
    
    <div class="form-flex-box form-map-box">
        <div class="form-map-addons">
            <p class="form-map-addon form-map-location">
                <span class="form-map-location-circle"></span> Lokalizacja:
                <span class="form-map-location-cord" id="cord-lat">50.2649 °N</span
                >,<span class="form-map-location-cord" id="cord-lon"> 19.0238 °E</span>
            </p>
            <p class="form-map-addon">Kliknij na mapie, aby zaznaczyć pinezkę.</p>
        </div>
        <div id="map" class="form-map"></div>
    </div>
    
    <div class="form-flex-box">
        <div class="form-data">
            <div class="form-input-box">
                <p class="form-input-box-label">
                    <i class="fa-solid fa-camera" style="color: #ff9b2f"></i>Zdjęcie
                </p>
                <div class="form-file-input">
                    <label asp-for="Photo" class="form-file-button">
                        Wybierz plik
                        <input asp-for="Photo" type="file" accept="image/png,image/jpeg,image/jpg" id="Photo"/>
                    </label>
                    <span class="form-file-name" id="file-name">Nie wybrano pliku</span>
                </div>
                <p class="form-input-types">*PNG, JPG, JPEG</p>
            </div>
            <div class="form-input-box">
                <label asp-for="Description" class="form-input-box-label" for=""><i class="fa-solid fa-file" style="color: #ff9b2f"></i> Opis
                    zwierzaka</label>
                <div class="textarea-wrapper">
                    <textarea asp-for="Description" placeholder="Opisz wygląd, rasę, kolor sierści, znaki szczególne oraz zachowanie zwierzęcia..." maxlength="500"></textarea>
                    <p class="textarea-counter">0/500</p>
                </div>
            </div>
            <div class="form-date-time-box">
                <div class="form-input-box">
                    <label asp-for="SeenDate" class="form-input-box-label">Data obserwacji</label>
                    <input asp-for="SeenDate" type="date"/>
                </div>
                <div class="form-input-box">
                    <label asp-for="SeenTime" class="form-input-box-label">Godzina obserwacji</label>
                    <input asp-for="SeenTime" type="time"/>
                </div>
            </div>
            <div asp-validation-summary="All" class="form-validation"></div>
        </div>
        <div class="form-footer">
            <button class="btn btn-primary" type="submit">
                @(Model.IsEdit ? "Zapisz zmiany" : "Dodaj doniesienie")
            </button>
        </div>
    </div>
</form>